In [1]:
import numpy.random as rd
import scipy.stats as st
import pylab
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

# Chi square test

In [2]:
data = pd.read_csv('bloodpressure.csv')
data.shape

(120, 5)

In [3]:
data

patient     sex agegrp  bp_before  bp_after
0          1    Male  30-45        143       153
1          2    Male  30-45        163       170
2          3    Male  30-45        153       168
3          4    Male  30-45        153       142
4          5    Male  30-45        146       141
..       ...     ...    ...        ...       ...
115      116  Female    60+        152       152
116      117  Female    60+        161       152
117      118  Female    60+        165       174
118      119  Female    60+        149       151
119      120  Female    60+        185       163

[120 rows x 5 columns]

In [4]:
import scipy.stats

In [5]:
df = sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# Observation Table

In [6]:
dataset_table = pd.crosstab(df['sex'],df['smoker'])
print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [7]:
dataset_table.values

array([[60, 97],
       [33, 54]], dtype=int64)

In [8]:
observed_values = dataset_table.values
print('observed values :-\n',observed_values)

observed values :-
 [[60 97]
 [33 54]]


In [9]:
import scipy.stats

In [10]:
val = scipy.stats.chi2_contingency(dataset_table)
val

(0.008763290531773594,
 0.925417020494423,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [12]:
val[1]

0.925417020494423

In [12]:
if val[1]<0.05:
    print('reject null, there is relationship between smoker and sex')
else:
    print('accept null, there is no relationship between smoker and sex')

accept null, there is no relationship between smoker and sex


# Anova

In [13]:
df1 = sns.load_dataset('iris')
df1

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [15]:
df_anova = df1[['petal_width','species']]

In [16]:
df_anova

petal_width    species
0            0.2     setosa
1            0.2     setosa
2            0.2     setosa
3            0.2     setosa
4            0.2     setosa
..           ...        ...
145          2.3  virginica
146          1.9  virginica
147          2.0  virginica
148          2.3  virginica
149          1.8  virginica

[150 rows x 2 columns]

In [18]:
df1.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [19]:
grps = pd.unique(df_anova.species.values)

In [20]:
grps

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [21]:
d_data = {grp:df_anova['petal_width'][df_anova.species ==grp] for grp in grps}

In [22]:
d_data

{'setosa': 0     0.2
 1     0.2
 2     0.2
 3     0.2
 4     0.2
 5     0.4
 6     0.3
 7     0.2
 8     0.2
 9     0.1
 10    0.2
 11    0.2
 12    0.1
 13    0.1
 14    0.2
 15    0.4
 16    0.4
 17    0.3
 18    0.3
 19    0.3
 20    0.2
 21    0.4
 22    0.2
 23    0.5
 24    0.2
 25    0.2
 26    0.4
 27    0.2
 28    0.2
 29    0.2
 30    0.2
 31    0.4
 32    0.1
 33    0.2
 34    0.2
 35    0.2
 36    0.2
 37    0.1
 38    0.2
 39    0.2
 40    0.3
 41    0.3
 42    0.2
 43    0.6
 44    0.4
 45    0.3
 46    0.2
 47    0.2
 48    0.2
 49    0.2
 Name: petal_width, dtype: float64,
 'versicolor': 50    1.4
 51    1.5
 52    1.5
 53    1.3
 54    1.5
 55    1.3
 56    1.6
 57    1.0
 58    1.3
 59    1.4
 60    1.0
 61    1.5
 62    1.0
 63    1.4
 64    1.3
 65    1.4
 66    1.5
 67    1.0
 68    1.5
 69    1.1
 70    1.8
 71    1.3
 72    1.5
 73    1.2
 74    1.3
 75    1.4
 76    1.4
 77    1.7
 78    1.5
 79    1.0
 80    1.1
 81    1.0
 82    1.2
 83    1.6
 84    1.5
 85  

In [23]:
F,p = scipy.stats.f_oneway(d_data['setosa'],d_data['versicolor'],d_data['virginica'])

In [25]:
F

960.007146801809

In [26]:
p

4.169445839443116e-85

In [32]:
print(round(p,4))

0.0


In [28]:
if p<0.05:
    print('reject null hypothsis')
else:
    print('accept null hypothesis')

reject null hypothsis
